### PR TITLE
prettyplease

### PR DESCRIPTION
**Pull request by burrbull**
I tried to add `format` option. But it looks like I cannot pass it to `write` function without global `static` as it is inside `syn fold`.
Do you have ideas?

### CODE REVIEW

**Comment by djmcgill** [comment]
Putting a bool into the `FileIntoMods` struct should work, if I'm understanding your question correctly.

**Comment by burrbull** [comment]
Really. I just was too tired yesterday to see obvious.

**Comment by burrbull** [comment]
Review, please

**Comment by djmcgill** [comment]
Looks good, if you could write a quick test that at least uses the true `fmt` option, even if it's not worth checking the actual formatting obviously. Absolutely worth having all code paths being called at least.

**Comment by djmcgill** [comment]
LGTM

**Comment by burrbull** [comment]
Could you release, please?

**Comment by djmcgill** [comment]
Done as 0.12.1

**Comment by burrbull** [comment]
> Done as 0.12.1

Add git tag too, please.

**Comment by djmcgill** [comment]
Done

**Comment by burrbull** [comment]
> Done

Thanks :). But could you make release from tag to deploy binaries?

**Comment by djmcgill** [comment]
Hmm. I forgot this project had released binaries. Let me remind myself.

**Comment by burrbull** [comment]
It is strange. It finishes CI with success and says "uploading artifact is complete" but no archive is present.

**Comment by djmcgill** [comment]
Well, I'll look into it but I wouldn't expect it tonight. But cargo install should still be fine, time for some local caching.

**Comment by djmcgill** [comment]
Right, that's the release tag and assets working finally.

**Pull request merged**
